name: Setup Node and Install Dependencies
description: "Handling nodejs setup and caching & installing Dependencies!"
inputs:
  node-version:
    description: "Specify nodejs version"
    required: false
    default: "22"
runs:
    using: composite
    steps:
        - name: Setup NodeJS env
          uses: actions/setup-node@v4 
          with:
              node-version: 22
        - name: Cache Dependencies
          uses: actions/cache@v4
          id: cache
          with:
              path: node_modules
              key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
        - name: Install NodeJS Dependencies
          shell: bash
          if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
          run: npm install
